[project]
site_name = "cappan"
site_description = "Font rendering engine implemented in pure Zig"
docs_dir = "cappan_doc/content"
site_dir = "docs"
repo_url = "https://github.com/heriet/cappan"

nav = [
  "index.md",
  { Guide = [
    "guide/cli.md",
    "guide/incremental-rendering.md",
    "guide/stroke-paint.md",
    "guide/developer-guide.md",
  ] },
  { Spec = [
    { "cappan_core" = [
      "spec/cappan_core/overview.md",
      "spec/cappan_core/font.md",
      "spec/cappan_core/layout.md",
      "spec/cappan_core/raster.md",
      "spec/cappan_core/render.md",
    ] },
    "spec/cappan_cli.md",
    "spec/cappan_subset.md",
    "spec/cappan_embed.md",
    "spec/cappan_inspect.md",
    "spec/cappan_pathify.md",
    "spec/cappan_metrics.md",
    "spec/error.md",
  ] },
]

[project.theme.icon]
repo = "fontawesome/brands/github"